export const USER_DATA_REQUEST = 'USER_DATA_REQUEST'
export const USER_DATA_SUCCESS = 'USER_DATA_SUCCESS'
export const USER_DATA_FAILURE = 'USER_DATA_FAILURE'

export const USER_ADD_COMMENT_REQUEST = 'USER_ADD_COMMENT_REQUEST'
export const USER_ADD_COMMENT_SUCCESS = 'USER_ADD_COMMENT_SUCCESS'
export const USER_ADD_COMMENT_FAILURE = 'USER_ADD_COMMENT_FAILURE'